In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data_set = pd.read_csv("Dataset.csv")

In [ ]:
data_set

Name  Speed/Min Assurance
0        1         33       Low
1        2         17       Low
2        3         23       Low
3        4          6      High
4        5         16       Low
...    ...        ...       ...
6356  6357         45       Low
6357  6358         18      High
6358  6359         58       Low
6359  6360         38       Low
6360  6361         12      High

[6361 rows x 3 columns]

In [ ]:
Assurance = {'High': 1, 'Low': 0}
#Assign these different key-value pair from above dictiionary to your table
data_set.Assurance = [Assurance[item] for item in data_set.Assurance]
#New table
print(data_set)

      Name  Speed/Min  Assurance
0        1         33          0
1        2         17          0
2        3         23          0
3        4          6          1
4        5         16          0
...    ...        ...        ...
6356  6357         45          0
6357  6358         18          1
6358  6359         58          0
6359  6360         38          0
6360  6361         12          1

[6361 rows x 3 columns]


In [ ]:
X = data_set.drop(['Assurance'], axis=1)

y = data_set['Assurance']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
X_train.shape, X_test.shape

((4452, 2), (1909, 2))

In [ ]:
categorical = [col for col in X_train.columns if X_train[col].dtypes == 'O']

categorical

[]

In [ ]:
numerical = [col for col in X_train.columns if X_train[col].dtypes != 'O']

numerical

['Name', 'Speed/Min']

In [ ]:
X_train[categorical].isnull().mean()

Series([], dtype: float64)

In [ ]:
for col in categorical:
    if X_train[col].isnull().mean()>0:
        print(col, (X_train[col].isnull().mean()))


In [ ]:
pip install category_encoders

In [ ]:
import category_encoders as ce

In [ ]:
X_train[categorical].head()

Empty DataFrame
Columns: []
Index: [4805, 88, 2036, 6072, 470]

In [ ]:
cols = X_train.columns

In [ ]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [ ]:
X_train = pd.DataFrame(X_train, columns=[cols])

In [ ]:
X_test = pd.DataFrame(X_test, columns=[cols])
X_train.head()

Name Speed/Min
0  0.506629 -0.354839
1 -0.973562 -0.774194
2 -0.362281 -0.612903
3  0.904213 -0.096774
4 -0.853691  0.741935

In [ ]:
from sklearn.naive_bayes import GaussianNB


# instantiate the model
gnb = GaussianNB()


# fit the model
gnb.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = gnb.predict(X_test)

y_pred

array([1, 1, 0, ..., 0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score

print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score: 0.9990


In [ ]:
#Compare the train-set and test-set accuracy
y_pred_train = gnb.predict(X_train)

y_pred_train

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 0.9998


In [ ]:
print('Training set score: {:.4f}'.format(gnb.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(gnb.score(X_test, y_test)))

Training set score: 0.9998
Test set score: 0.9990


In [ ]:
y_test.value_counts()

0    1326
1     583
Name: Assurance, dtype: int64

In [ ]:
null_accuracy = (7407/(7407+2362))
print(null_accuracy)

0.7582147609786057


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1324    2]
 [   0  583]]


0.998952331063384